// packages/ui/src/components/ui/label/label.svelte
<script lang="ts">
   import { Label as LabelPrimitive } from "bits-ui";

   import { cn } from "@ota/ui/utils.js";

   let {
      ref = $bindable(null),
      class: className,
      ...restProps
   }: LabelPrimitive.RootProps = $props();
</script>

<LabelPrimitive.Root
   bind:ref
   data-slot="label"
   class={cn(
      "flex items-center gap-2 text-sm leading-none font-medium select-none group-data-[disabled=true]:pointer-events-none group-data-[disabled=true]:opacity-50 peer-disabled:cursor-not-allowed peer-disabled:opacity-50",
      className,
   )}
   {...restProps}
/>

// packages/ui/src/ui/label.tsx
"use client";

import { Label as LabelPrimitive } from "radix-ui";

import { cn } from "@ota/ui";

export function Label({
   className,
   ...props
}: React.ComponentProps<typeof LabelPrimitive.Root>) {
   return (
      <LabelPrimitive.Root
         data-slot="label"
         className={cn(
            "flex items-center gap-2 text-sm leading-none font-medium select-none group-data-[disabled=true]:pointer-events-none group-data-[disabled=true]:opacity-50 peer-disabled:cursor-not-allowed peer-disabled:opacity-50",
            className,
         )}
         {...props}
      />
   );
}
